// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svhherbceqsccikhyqmq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2aGhlcmJjZXFzY2Npa2h5cW1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNDA1NTAsImV4cCI6MjA3MDcxNjU1MH0.1Wc2p9L76N6wNFmAfSnIn0YJKlKV6qgTpDL1hgVm8co";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});